language: python
python:
- 2.6
- 2.7
install:
- pip install coveralls
script:
- nosetests --cover-package=pyblish --with-doctest --with-coverage --exclude=vendor
- pip install git+git://github.com/abstractfactory/pyblish.git
after_success:
- coveralls
deploy:
  provider: pypi
  user: mottosso
  distributions: "sdist"
  password:
    secure: eTeJjM9nWt1IBIlLVdpZmCwy9KbNy91EG4VfJU4+Y7bWQ1OoBGAi8ijZ9twNq3tnQL1/KdLo/3w8fn4r0UopNug7IDQhGUFdzoq2vXMDUtvSqU5ol01jr4fPb51dIYtcJJRZJbjgcc7nNZyiZ6ybAFciouroPsraAlTWXgbWiv4=
  on:
    tags: true
    all_branches: true
    repo: abstractfactory/pyblish
